# Use the httpd-parent image as base
FROM quay.io/redhattraining/httpd-parent

# label 8080
#
#
RUN sed -i "s/Listen 80/Listen 8080/g" /etc/httpd/conf/httpd.conf && \
   # sed -i "s/#server Name www.example.com:80/#servername 0.0.0.0:8080" /etc/httpd/conf/httpd.conf && \
    chgrp -R 0 /var/log/httpd /var/run/httpd && \
    chmod -R g=u /var/log/httpd /var/run/httpd 

ONBUILD COPY /src/ /etc/www/html 
USER 1001
EXPOSE 8080 
   
